# Generated by Django 4.1.2 on 2023-02-03 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 4, 0, 58, 37, 632842)),
        ),
    ]
